#!/usr/bin/env bash
set -euo pipefail

DCE_HOSTNAME="${DCE_HOSTNAME:-http://10.0.6.152:30448/}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
DEFAULT_DCE_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJpN2g3QzgzbXFwZDlRYXRsbGNiWTh6MXdqbERYX2kyTDBMbFkwRmVMaUowIn0.eyJleHAiOjE3ODE3MDYxOTQsImlhdCI6MTc4MTYxOTc5NCwiYXV0aF90aW1lIjoxNzgxNjE5MTkyLCJqdGkiOiJjOTllMTY2Mi0xMWQwLTQyYzktYjMwMS01OTY0OWEzNWM5MjAiLCJpc3MiOiJodHRwczovLzEwLjAuNi4xNTI6MzAyNjIvYXV0aC9yZWFsbXMvZ2hpcHBvIiwiYXVkIjoiX19pbnRlcm5hbC1naGlwcG8iLCJzdWIiOiI1MjdlMDU5OC02NjUzLTQ3MzAtYTgwNy03N2ZlNzFlZmU3MGQiLCJ0eXAiOiJJRCIsImF6cCI6Il9faW50ZXJuYWwtZ2hpcHBvIiwic2Vzc2lvbl9zdGF0ZSI6IjA0MGMwYWUyLWExOGUtNDI0Mi04OWU3LWM1YTFhMGM2YjUzYyIsImF0X2hhc2giOiJpS0NyQkRrYTJtc2tsQjdMYW84OXhRIiwiYWNyIjoiMSIsInNpZCI6IjA0MGMwYWUyLWExOGUtNDI0Mi04OWU3LWM1YTFhMGM2YjUzYyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiY2xpZW50SG9zdCI6IjEwLjAuNi4xNTI6MzA0NDgiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImdpdmVuX25hbWUiOiIiLCJsb2NhbGUiOiIifQ.IATZ_EYmeWYUmXetHvNyvW5lGqYcLc9QXEtVM4Imu8gEPQmzfRKZOxSUes6gtK3220qZJEa1SDwhHeUcMxxC7QQ738YXYLk0Rha0mn32BZmtOHQp1suF1dSzezmSaxTK1a5O5d4d1sAMTii17OTbRgiEgC-W1xEmTusXgCZyIfgNvxh_FRYxTR6VOyJ8cbb1TuGGNZDVv_3-i4iBA_ueZyBoLaGIap_Cl7TSsMbOpo8eYP7HZGk159G2DmrSsvCuKWIZ_C8c-FKfKEN6B5Wg3jJ_4Rp7lpY-aOIDTdC2ZmoCM-PiiWBo-HIhMmonTcVQjOLiegDRVSFt-mOE7klVjw"

DCE_TOKEN="${DCE_TOKEN:-${DEFAULT_DCE_TOKEN}}"


printf '%s' "${DCE_TOKEN}" | "${K8S_AI_BENCH_REPO_ROOT:-${REPO_ROOT}}/clis/dce" auth login \
  --hostname "${DCE_HOSTNAME}" \
  --with-token
